1st attempt at updating with caddy.

diff --git a/.github/workflows/create_docker_image.yml b/.github/workflows/create_docker_image.yml
--- a/.github/workflows/create_docker_image.yml
+++ b/.github/workflows/create_docker_image.yml
@@ -7,7 +7,6 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout
       uses: actions/checkout@v4
@@ -19,12 +18,24 @@ jobs:
         echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
         # echo "::set-output name=output::$DATE"
 
-    - name: Get release tag
-      id: release
+    - name: Set BASE_IMAGE and GH_TAG
+      id: tag
       run: |
-        buildTag=$(date +%Y-%m-%d-%H-%M)
-        echo "GH_TAG=$buildTag" >> $GITHUB_OUTPUT
-
+        if [ "${{ github.event.inputs.base_image }}" == "alpine" ]; then
+          echo "BASE_IMAGE=alpine:latest" >> $GITHUB_ENV
+          buildTag=$(date +%Y-%m-%d-%H-%M)
+          echo "GH_TAG=$buildTag" >> $GITHUB_OUTPUT
+        elif [ "${{ github.event.inputs.base_image }}" == "caddy" ]; then
+            echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_ENV
+            echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}" >> $GITHUB_ENV
+        elif [ "${{ github.event.inputs.base_image }}" == "caddy-s6" ]; then
+          echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_ENV
+          echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}-s6" >> $GITHUB_ENV
+        else
+          echo "Invalid base image specified" >&2
+          exit 1
+        fi
+  
     - name: Login to DockerHub
       uses: docker/login-action@v3 
       with:
@@ -45,7 +56,7 @@ jobs:
         push: true
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
         tags: |
-          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.release.outputs.GH_TAG }}
+          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_TAG }}
           ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:latest
         build-args: |
           BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
